#!/bin/bash

file="$1"

if [ ! ${file: -6} == ".ipynb" ] ; then
    exit 0
fi

if [[ $file =~ "nbsearch-tmp" ]] ; then
    exit 0
fi

if [[ -f /home/$NB_USER/.nbsearch/config_local.py ]] ; then
    exit 0
fi

jupyter nbsearch update-index --debug /home/$NB_USER/.jupyter/jupyter_notebook_config.py local $file
exit 0
